# left-side user profile
avatar: https://avatars3.githubusercontent.com/u/8843214?s=460&v=4 
location: China
email: msjdxhc@gmail.com
social:
  github: https://github.com/AlanJager

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code
